-- MySQL Script generated by MySQL Workbench
-- Tue Jan 23 18:31:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema project_oracle_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project_oracle_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_oracle_db` DEFAULT CHARACTER SET utf8 ;
USE `project_oracle_db` ;

-- -----------------------------------------------------
-- Table `project_oracle_db`.`user_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`user_client` (
  `id_user_client` INT NOT NULL AUTO_INCREMENT,
  `pseudo_client` VARCHAR(100) NOT NULL,
  `tel_user_client` VARCHAR(50) NOT NULL,
  `password_client` VARCHAR(500) NOT NULL,
  `statut_user_client` VARCHAR(45) NOT NULL,
  `created_cl_user` DATETIME NOT NULL,
  `updated_cl_user` DATETIME NULL,
  `statut_cl_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user_client`),
  UNIQUE INDEX `id_client_UNIQUE` (`id_user_client` ASC),
  UNIQUE INDEX `tel_client_UNIQUE` (`tel_user_client` ASC),
  UNIQUE INDEX `pseudo_client_UNIQUE` (`pseudo_client` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`clients_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`clients_info` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom_client` VARCHAR(50) NOT NULL,
  `prenom_client` VARCHAR(100) NOT NULL,
  `naissance_client` DATE NOT NULL,
  `nif_client` VARCHAR(50) NULL,
  `cin_client` VARCHAR(50) NULL,
  `sexe_client` VARCHAR(10) NOT NULL,
  `civilite_client` VARCHAR(50) NOT NULL,
  `created_client` DATETIME NOT NULL,
  `updated_client` DATETIME NULL,
  `userClientID` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `id_client_UNIQUE` (`id_client` ASC),
  UNIQUE INDEX `nif_client_UNIQUE` (`nif_client` ASC),
  UNIQUE INDEX `cin_client_UNIQUE` (`cin_client` ASC),
  INDEX `u_idx` (`userClientID` ASC),
  CONSTRAINT `foreign_key_reference_cl_user`
    FOREIGN KEY (`userClientID`)
    REFERENCES `project_oracle_db`.`user_client` (`id_user_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`adresse_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`adresse_client` (
  `id_cl_adresse` INT NOT NULL AUTO_INCREMENT,
  `type_cl_adresse` VARCHAR(45) NOT NULL,
  `desc_cl_adresse` VARCHAR(45) NOT NULL,
  `adrClientID` INT NOT NULL,
  `created_cl_adr` DATETIME NOT NULL,
  `updated_cl_adr` DATETIME NULL,
  PRIMARY KEY (`id_cl_adresse`),
  UNIQUE INDEX `id_adresse_UNIQUE` (`id_cl_adresse` ASC),
  INDEX `foreign_key_reference_client_idx` (`adrClientID` ASC),
  CONSTRAINT `foreign_key_reference_adr_client`
    FOREIGN KEY (`adrClientID`)
    REFERENCES `project_oracle_db`.`clients_info` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`telephone_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`telephone_client` (
  `id_cl_telephone` INT NOT NULL AUTO_INCREMENT,
  `type_cl_telephone` VARCHAR(45) NULL,
  `desc_cl_telephone` VARCHAR(45) NULL,
  `telClientID` INT NOT NULL,
  `created_cl_telephone` DATETIME NOT NULL,
  `updated_cl_telephone` DATETIME NULL,
  PRIMARY KEY (`id_cl_telephone`),
  UNIQUE INDEX `id_telephone_UNIQUE` (`id_cl_telephone` ASC),
  UNIQUE INDEX `desc_telephone_UNIQUE` (`desc_cl_telephone` ASC),
  INDEX `foreign_key_reference_tel_client_idx` (`telClientID` ASC),
  CONSTRAINT `foreign_key_reference_tel_client`
    FOREIGN KEY (`telClientID`)
    REFERENCES `project_oracle_db`.`clients_info` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`email_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`email_client` (
  `id_cl_email` INT NOT NULL,
  `type_cl_email` VARCHAR(45) NULL,
  `desc_cl_email` VARCHAR(45) NULL,
  `mailClientID` INT NOT NULL,
  `created_cl_email` DATETIME NOT NULL,
  `updated_cl_client` DATETIME NULL,
  PRIMARY KEY (`id_cl_email`),
  UNIQUE INDEX `desc_email_UNIQUE` (`desc_cl_email` ASC),
  INDEX `foreign_key_reference_mail_client_idx` (`mailClientID` ASC),
  CONSTRAINT `foreign_key_reference_mail_client`
    FOREIGN KEY (`mailClientID`)
    REFERENCES `project_oracle_db`.`clients_info` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`type_compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`type_compte` (
  `id_type_compte` INT NOT NULL AUTO_INCREMENT,
  `desc_type_compte` VARCHAR(100) NULL,
  `plafond_semaine` DOUBLE NOT NULL,
  `created_tcompte` DATETIME NOT NULL,
  `updated_tcompte` DATETIME NULL,
  PRIMARY KEY (`id_type_compte`),
  UNIQUE INDEX `id_type_compte_UNIQUE` (`id_type_compte` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`agence_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`agence_info` (
  `id_agence` INT NOT NULL AUTO_INCREMENT,
  `nom_agence` VARCHAR(45) NOT NULL,
  `adr_agence` VARCHAR(45) NOT NULL,
  `tel_agence` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_agence`),
  UNIQUE INDEX `id_agence_UNIQUE` (`id_agence` ASC),
  UNIQUE INDEX `nom_agence_UNIQUE` (`nom_agence` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`user_employer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`user_employer` (
  `id_user_emp` INT NOT NULL AUTO_INCREMENT,
  `pseudo_emp` VARCHAR(45) NOT NULL,
  `tel_user_emp` VARCHAR(45) NOT NULL,
  `password_emp` VARCHAR(45) NOT NULL,
  `created_emp_user` DATETIME NOT NULL,
  `updated_emp_user` DATETIME NULL,
  `statut_emp_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user_emp`),
  UNIQUE INDEX `id_user_emp_UNIQUE` (`id_user_emp` ASC),
  UNIQUE INDEX `pseudo_emp_UNIQUE` (`pseudo_emp` ASC),
  UNIQUE INDEX `tel_user_emp_UNIQUE` (`tel_user_emp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`employer_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`employer_info` (
  `id_employer` INT NOT NULL AUTO_INCREMENT,
  `nom_emp` VARCHAR(45) NOT NULL,
  `prenom_emp` VARCHAR(45) NOT NULL,
  `sexe_emp` VARCHAR(45) NOT NULL,
  `civilite_emp` VARCHAR(45) NOT NULL,
  `naissance_emp` DATE NOT NULL,
  `nif_emp` VARCHAR(45) NULL,
  `cin_emp` VARCHAR(45) NULL,
  `userEmpID` INT NOT NULL,
  `agenceEmpID` INT NOT NULL,
  `created_emp` DATETIME NOT NULL,
  `updated_emp` DATETIME NULL,
  PRIMARY KEY (`id_employer`),
  UNIQUE INDEX `id_employer_UNIQUE` (`id_employer` ASC),
  UNIQUE INDEX `nif_emp_UNIQUE` (`nif_emp` ASC),
  UNIQUE INDEX `cin_emp_UNIQUE` (`cin_emp` ASC),
  UNIQUE INDEX `userEmpID_UNIQUE` (`userEmpID` ASC),
  UNIQUE INDEX `agenceEmpID_UNIQUE` (`agenceEmpID` ASC),
  CONSTRAINT `foreign_key_reference_emp_user`
    FOREIGN KEY (`userEmpID`)
    REFERENCES `project_oracle_db`.`user_employer` (`id_user_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_key_reference_emp_agence`
    FOREIGN KEY (`agenceEmpID`)
    REFERENCES `project_oracle_db`.`agence_info` (`id_agence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`compte` (
  `id_compte` INT NOT NULL,
  `iban_compte` VARCHAR(45) NOT NULL,
  `bic_compte` VARCHAR(45) NOT NULL,
  `typeCompteID` INT NOT NULL,
  `solde_compte` DOUBLE NOT NULL,
  `compteClientID` INT NOT NULL,
  `compteAgenceID` INT NOT NULL,
  `compteEmployerID` INT NOT NULL,
  `created_compte` DATETIME NOT NULL,
  `updated_compte` DATETIME NULL,
  PRIMARY KEY (`id_compte`),
  INDEX `foreign_key_reference_compte_client_idx` (`compteClientID` ASC),
  INDEX `foreign_key_reference_type_compte_client_idx` (`typeCompteID` ASC),
  INDEX `foreign_key_reference_agence_client_idx` (`compteAgenceID` ASC),
  INDEX `foreign_key_reference_emp_client_idx` (`compteEmployerID` ASC),
  CONSTRAINT `foreign_key_reference_compte_client`
    FOREIGN KEY (`compteClientID`)
    REFERENCES `project_oracle_db`.`clients_info` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_key_reference_type_compte_client`
    FOREIGN KEY (`typeCompteID`)
    REFERENCES `project_oracle_db`.`type_compte` (`id_type_compte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_key_reference_agence_client`
    FOREIGN KEY (`compteAgenceID`)
    REFERENCES `project_oracle_db`.`agence_info` (`id_agence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_key_reference_emp_client`
    FOREIGN KEY (`compteEmployerID`)
    REFERENCES `project_oracle_db`.`employer_info` (`id_employer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`adresse_employer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`adresse_employer` (
  `id_emp_adresse` INT NOT NULL AUTO_INCREMENT,
  `type_emp_adresse` VARCHAR(45) NOT NULL,
  `desc_emp_adresse` VARCHAR(45) NOT NULL,
  `adrEmpID` INT NOT NULL,
  `created_emp_adr` DATETIME NOT NULL,
  `updated_emp_adr` DATETIME NULL,
  PRIMARY KEY (`id_emp_adresse`),
  UNIQUE INDEX `id_emp_adresse_UNIQUE` (`id_emp_adresse` ASC),
  INDEX `foreign_key_reference_adr_emp_idx` (`adrEmpID` ASC),
  CONSTRAINT `foreign_key_reference_adr_emp`
    FOREIGN KEY (`adrEmpID`)
    REFERENCES `project_oracle_db`.`employer_info` (`id_employer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`email_employer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`email_employer` (
  `id_emp_email` INT NOT NULL AUTO_INCREMENT,
  `type_emp_email` VARCHAR(45) NOT NULL,
  `desc_emp_email` VARCHAR(45) NOT NULL,
  `emailEmpID` INT NOT NULL,
  `created_emp_email` DATETIME NOT NULL,
  `updated_emp_email` DATETIME NULL,
  PRIMARY KEY (`id_emp_email`),
  UNIQUE INDEX `id_emp_email_UNIQUE` (`id_emp_email` ASC),
  INDEX `foreign_key_reference_mail_emp_idx` (`emailEmpID` ASC),
  CONSTRAINT `foreign_key_reference_mail_emp`
    FOREIGN KEY (`emailEmpID`)
    REFERENCES `project_oracle_db`.`employer_info` (`id_employer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`telephone_emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`telephone_emp` (
  `id_emp_tel` INT NOT NULL AUTO_INCREMENT,
  `type_emp_tel` VARCHAR(45) NOT NULL,
  `desc_emp_tel` VARCHAR(45) NOT NULL,
  `telEmpID` INT NOT NULL,
  PRIMARY KEY (`id_emp_tel`),
  UNIQUE INDEX `id_emp_tel_UNIQUE` (`id_emp_tel` ASC),
  INDEX `foreign_key_reference_tel_emp_idx` (`telEmpID` ASC),
  CONSTRAINT `foreign_key_reference_tel_emp`
    FOREIGN KEY (`telEmpID`)
    REFERENCES `project_oracle_db`.`employer_info` (`id_employer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`type_fonction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`type_fonction` (
  `id_type_fonction` INT NOT NULL AUTO_INCREMENT,
  `desc_type_fonctioncol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type_fonction`),
  UNIQUE INDEX `desc_type_fonctioncol_UNIQUE` (`desc_type_fonctioncol` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_oracle_db`.`fonction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_oracle_db`.`fonction` (
  `id_fonction` INT NOT NULL AUTO_INCREMENT,
  `empFoncID` INT NOT NULL,
  `typeFoncID` INT NOT NULL,
  PRIMARY KEY (`id_fonction`),
  UNIQUE INDEX `id_fonction_UNIQUE` (`id_fonction` ASC),
  INDEX `foreign_key_reference_emp_fonction_idx` (`empFoncID` ASC),
  INDEX `foreign_key_reference_type_fonction_idx` (`typeFoncID` ASC),
  CONSTRAINT `foreign_key_reference_emp_fonction`
    FOREIGN KEY (`empFoncID`)
    REFERENCES `project_oracle_db`.`employer_info` (`id_employer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_key_reference_type_fonction`
    FOREIGN KEY (`typeFoncID`)
    REFERENCES `project_oracle_db`.`type_fonction` (`id_type_fonction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
