-- MySQL Script generated by MySQL Workbench
-- Sat Mar  3 02:48:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema p_final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema p_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p_final` DEFAULT CHARACTER SET utf8 ;
USE `p_final` ;

-- -----------------------------------------------------
-- Table `p_final`.`agence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`agence` (
  `idagence` INT NOT NULL AUTO_INCREMENT,
  `type_agence` VARCHAR(45) NOT NULL DEFAULT 'SUCCURSALE',
  `tel_agence` INT(11) NOT NULL,
  `adresse_agence` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idagence`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`type_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`type_user` (
  `idtype_user` INT NOT NULL AUTO_INCREMENT,
  `description_type_user` VARCHAR(45) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_mise_a_jour` DATETIME NOT NULL,
  PRIMARY KEY (`idtype_user`),
  UNIQUE INDEX `idtype_user_UNIQUE` (`idtype_user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`employe` (
  `idemploye` INT NOT NULL AUTO_INCREMENT,
  `nom_emp` VARCHAR(45) NOT NULL,
  `prenom_emp` VARCHAR(45) NOT NULL,
  `sexe_emp` VARCHAR(7) NOT NULL,
  `civilite_emp` VARCHAR(6) NOT NULL,
  `nif_emp` INT(10) NOT NULL,
  `cin_emp` INT(15) NULL,
  `user_emp_id` INT NOT NULL,
  `type_user_id` INT NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_mise_a_jour` DATETIME NULL,
  `id_succursale` INT NOT NULL,
  PRIMARY KEY (`idemploye`),
  INDEX `fk_employe_info_agence_info_idx` (`id_succursale` ASC),
  UNIQUE INDEX `type_user_id_UNIQUE` (`type_user_id` ASC),
  UNIQUE INDEX `user_emp_id_UNIQUE` (`user_emp_id` ASC),
  CONSTRAINT `fk_employe_agence`
    FOREIGN KEY (`id_succursale`)
    REFERENCES `p_final`.`agence` (`idagence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employe_type_user`
    FOREIGN KEY (`type_user_id`)
    REFERENCES `p_final`.`type_user` (`idtype_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`fonction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`fonction` (
  `idfonction` INT NOT NULL AUTO_INCREMENT,
  `desc_fonctoin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfonction`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`employe_fonction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`employe_fonction` (
  `idemploye_fonction` INT NOT NULL AUTO_INCREMENT,
  `emp_fonc_id` INT NULL,
  `fonction_id` INT NULL,
  `date_creation` DATETIME NULL,
  PRIMARY KEY (`idemploye_fonction`),
  INDEX `emp_fonc_id_idx` (`emp_fonc_id` ASC),
  INDEX `fk_employe_fonction_fonction_idx` (`fonction_id` ASC),
  CONSTRAINT `fk_employe_fonction_employe_info`
    FOREIGN KEY (`emp_fonc_id`)
    REFERENCES `p_final`.`employe` (`idemploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employe_fonction_fonction`
    FOREIGN KEY (`fonction_id`)
    REFERENCES `p_final`.`fonction` (`idfonction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `nom_client` VARCHAR(45) NOT NULL,
  `prenom_client` VARCHAR(45) NOT NULL,
  `naissance_client` INT NOT NULL,
  `nif_client` INT(10) NOT NULL,
  `cin_client` INT(10) NOT NULL,
  `sexe_client` VARCHAR(7) NOT NULL,
  `civilite_client` VARCHAR(11) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_mise_a_jour` DATETIME NOT NULL,
  `id_user_client` INT NOT NULL,
  `type_user_client_id` INT NOT NULL,
  `id_succursale` INT NULL,
  PRIMARY KEY (`idclient`),
  INDEX `fk_client_agence_idx` (`id_succursale` ASC),
  UNIQUE INDEX `id_user_client_UNIQUE` (`id_user_client` ASC),
  UNIQUE INDEX `type_user_client_id_UNIQUE` (`type_user_client_id` ASC),
  CONSTRAINT `fk_client_agence`
    FOREIGN KEY (`id_succursale`)
    REFERENCES `p_final`.`agence` (`idagence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_type_user`
    FOREIGN KEY (`id_user_client`)
    REFERENCES `p_final`.`type_user` (`idtype_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `id_type_user` INT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_mise_a_jour` DATETIME NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC),
  INDEX `fk_user_type_user_idx` (`id_type_user` ASC),
  CONSTRAINT `fk_user_type_user`
    FOREIGN KEY (`id_type_user`)
    REFERENCES `p_final`.`type_user` (`idtype_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`types_informations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`types_informations` (
  `idtypes_informations` INT NOT NULL AUTO_INCREMENT,
  `description_type_infos` VARCHAR(45) NULL,
  PRIMARY KEY (`idtypes_informations`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`telephone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`telephone` (
  `idtelephone` INT NOT NULL AUTO_INCREMENT,
  `id_type_telephone` INT NOT NULL,
  `id_proprietaire` INT NULL,
  `numero_telephone` INT(11) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_mise_a_jour` DATETIME NOT NULL,
  PRIMARY KEY (`idtelephone`),
  UNIQUE INDEX `id_proprietaire_UNIQUE` (`id_proprietaire` ASC),
  INDEX `fk_telephone_types_informations_idx` (`id_type_telephone` ASC),
  CONSTRAINT `fk_telephone_user`
    FOREIGN KEY (`id_proprietaire`)
    REFERENCES `p_final`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telephone_types_informations`
    FOREIGN KEY (`id_type_telephone`)
    REFERENCES `p_final`.`types_informations` (`idtypes_informations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`adresse` (
  `idadresse` INT NOT NULL AUTO_INCREMENT,
  `id_type_adresse` INT NOT NULL,
  `description_adresse` VARCHAR(255) NOT NULL,
  `nom_proprietaire_id` INT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_mise_a_jour` DATETIME NOT NULL,
  PRIMARY KEY (`idadresse`),
  UNIQUE INDEX `nom_proprietaire_id_UNIQUE` (`nom_proprietaire_id` ASC),
  INDEX `fk_adresse_type_information_idx` (`id_type_adresse` ASC),
  CONSTRAINT `fk_adresse_user`
    FOREIGN KEY (`nom_proprietaire_id`)
    REFERENCES `p_final`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adresse_type_information`
    FOREIGN KEY (`id_type_adresse`)
    REFERENCES `p_final`.`types_informations` (`idtypes_informations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`email` (
  `idemail` INT NOT NULL AUTO_INCREMENT,
  `nom_proprietaire_id` INT NULL,
  `date_creation` DATETIME NULL,
  `date_mise_a_jour` DATETIME NULL,
  PRIMARY KEY (`idemail`),
  UNIQUE INDEX `idemail_UNIQUE` (`idemail` ASC),
  INDEX `fk_email_user_idx` (`nom_proprietaire_id` ASC),
  CONSTRAINT `fk_email_user`
    FOREIGN KEY (`nom_proprietaire_id`)
    REFERENCES `p_final`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`type_compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`type_compte` (
  `idtype_compte` INT NOT NULL AUTO_INCREMENT,
  `desc_type_compte` VARCHAR(50) NOT NULL,
  `plafond_semaine` DECIMAL(50) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_mise_a_jour` DATETIME NOT NULL,
  PRIMARY KEY (`idtype_compte`),
  UNIQUE INDEX `idtype_compte_UNIQUE` (`idtype_compte` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`compte` (
  `idcompte` INT(9) NOT NULL,
  `iban` VARCHAR(34) NOT NULL,
  `bic` VARCHAR(11) NOT NULL,
  `type_compte_id` INT NOT NULL,
  `id_proprietaire` INT NOT NULL,
  `solde_compte` DOUBLE NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `id_employe` INT NULL,
  PRIMARY KEY (`idcompte`, `type_compte_id`),
  UNIQUE INDEX `idcompte_UNIQUE` (`idcompte` ASC),
  UNIQUE INDEX `iban_UNIQUE` (`iban` ASC),
  INDEX `fk_compte_employe_idx` (`id_employe` ASC),
  INDEX `fk_compte_type_compte_idx` (`type_compte_id` ASC),
  CONSTRAINT `fk_compte_employe`
    FOREIGN KEY (`id_employe`)
    REFERENCES `p_final`.`employe` (`idemploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compte_type_compte`
    FOREIGN KEY (`type_compte_id`)
    REFERENCES `p_final`.`type_compte` (`idtype_compte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`resiliation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`resiliation` (
  `idresiliation` INT NOT NULL AUTO_INCREMENT,
  `compte_id` INT NOT NULL,
  `proprietaire_id` INT NOT NULL,
  `type_proprietaire_id` INT NOT NULL,
  `date_creation` DATETIME NOT NULL,
  PRIMARY KEY (`idresiliation`),
  UNIQUE INDEX `idresiliation_UNIQUE` (`idresiliation` ASC),
  INDEX `fk_resiliation_proprietaire_idx` (`proprietaire_id` ASC),
  INDEX `fk_resiliation_compte_idx` (`compte_id` ASC),
  CONSTRAINT `fk_resiliation_client`
    FOREIGN KEY (`proprietaire_id`)
    REFERENCES `p_final`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resiliation_employe`
    FOREIGN KEY (`proprietaire_id`)
    REFERENCES `p_final`.`employe` (`idemploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resiliation_compte`
    FOREIGN KEY (`compte_id`)
    REFERENCES `p_final`.`compte` (`idcompte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`type_carte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`type_carte` (
  `description_type_carte` VARCHAR(45) NULL,
  `id_type_carte` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_type_carte`),
  UNIQUE INDEX `type_cartecol_UNIQUE` (`id_type_carte` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`carte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`carte` (
  `idcarte` INT NOT NULL AUTO_INCREMENT,
  `id_compte` INT NOT NULL,
  `code_secret` INT(4) NOT NULL,
  `date_fabrication` DATE NOT NULL,
  `date_mise_en_circulation` DATE NOT NULL,
  `type_carte` INT NOT NULL,
  PRIMARY KEY (`idcarte`),
  UNIQUE INDEX `idcarte_UNIQUE` (`idcarte` ASC),
  INDEX `fk_carte_compte_idx` (`id_compte` ASC),
  INDEX `fk_carte_type_carte_idx` (`type_carte` ASC),
  CONSTRAINT `fk_carte_compte`
    FOREIGN KEY (`id_compte`)
    REFERENCES `p_final`.`compte` (`idcompte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carte_type_carte`
    FOREIGN KEY (`type_carte`)
    REFERENCES `p_final`.`type_carte` (`id_type_carte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`type_transcation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`type_transcation` (
  `idtype_transcation` INT NOT NULL AUTO_INCREMENT,
  `description_type_transaction` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtype_transcation`),
  UNIQUE INDEX `idtype_transcation_UNIQUE` (`idtype_transcation` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`transaction` (
  `idtransaction` INT NOT NULL AUTO_INCREMENT,
  `type_transaction_id` INT NULL,
  `montant_transaction` DOUBLE NOT NULL,
  `compte_donneur_id` INT(9) NULL,
  `compte_beneficiaire_id` INT(9) NULL,
  `information_textuelle` VARCHAR(255) NULL,
  `message_communication` LONGTEXT NULL,
  `date_creation` DATETIME NULL,
  PRIMARY KEY (`idtransaction`),
  UNIQUE INDEX `idtransaction_UNIQUE` (`idtransaction` ASC),
  INDEX `fk_transaction_type_transaction_idx` (`type_transaction_id` ASC),
  INDEX `fk_transaction_compte_idx` (`compte_donneur_id` ASC),
  INDEX `fk_transaction_beneficiare_compte_idx` (`compte_beneficiaire_id` ASC),
  CONSTRAINT `fk_transaction_type_transaction`
    FOREIGN KEY (`type_transaction_id`)
    REFERENCES `p_final`.`type_transcation` (`idtype_transcation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_donneur_compte`
    FOREIGN KEY (`compte_donneur_id`)
    REFERENCES `p_final`.`compte` (`idcompte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_beneficiare_compte`
    FOREIGN KEY (`compte_beneficiaire_id`)
    REFERENCES `p_final`.`compte` (`idcompte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`type_credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`type_credit` (
  `idtype_credit` INT NOT NULL AUTO_INCREMENT,
  `description_type_credit` VARCHAR(45) NOT NULL,
  `valeur_minimum_montant` FLOAT(50) NOT NULL,
  `duree_minimum_remboursement` INT(5) NOT NULL,
  PRIMARY KEY (`idtype_credit`),
  UNIQUE INDEX `idtype_credit_UNIQUE` (`idtype_credit` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`remboursement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`remboursement` (
  `idremboursement` INT NOT NULL AUTO_INCREMENT,
  `type_remboursement` VARCHAR(45) NULL,
  `duree_remboursement` INT(5) NULL,
  `remboursementcol` VARCHAR(45) NULL,
  UNIQUE INDEX `idremboursement_UNIQUE` (`idremboursement` ASC),
  PRIMARY KEY (`idremboursement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`credit` (
  `idcredit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idcompte` INT NULL,
  `idremboursement` INT NULL,
  `id_type_credit` INT NULL,
  `montant_emprunt` FLOAT(45) NULL,
  `interet` FLOAT(45) NULL,
  `date_creation` DATE NULL,
  PRIMARY KEY (`idcredit`),
  INDEX `fk_credit_compte_idx` (`idcompte` ASC),
  INDEX `fk_credit_type_credit_idx` (`id_type_credit` ASC),
  INDEX `fk_credit_remboursement_idx` (`idremboursement` ASC),
  CONSTRAINT `fk_credit_compte`
    FOREIGN KEY (`idcompte`)
    REFERENCES `p_final`.`compte` (`idcompte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_credit_type_credit`
    FOREIGN KEY (`id_type_credit`)
    REFERENCES `p_final`.`type_credit` (`idtype_credit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_credit_remboursement`
    FOREIGN KEY (`idremboursement`)
    REFERENCES `p_final`.`remboursement` (`idremboursement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p_final`.`tarif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p_final`.`tarif` (
  `idtarif` INT NOT NULL AUTO_INCREMENT,
  `idremboursement` INT NOT NULL,
  `taux_reel_annuel` INT(9) NULL,
  PRIMARY KEY (`idtarif`),
  INDEX `fk_tarif_remboursement_idx` (`idremboursement` ASC),
  CONSTRAINT `fk_tarif_remboursement`
    FOREIGN KEY (`idremboursement`)
    REFERENCES `p_final`.`remboursement` (`idremboursement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
